### ISSUE TITLE
Event Priorities prevent overriding Boot.Codes

### ISSUE THREAD

**Issue by XtraCube** [miniduikboot/Boot.Codes#3]
Remove or change the event priorities to allow overriding codes generated by Boot.Codes

**Comment by miniduikboot** [comment]
Actually because Boot.Codes has a higher priority, events with a lower priority will run after it. If you want to run your plugin before Boot.Codes, run it at EventPriority.Monitor. I'm keeping this current priority for compatibility reasons.

Overwriting the codes from Boot.Codes will however lead to a pool drain, and I've raised https://github.com/miniduikboot/Boot.Codes/pull/4 to fix that

tl;dr you can override Boot.Codes but it makes Boot.Codes sad and eventually give up unless this PR is merged
